% Auto-generated by cameraCalibrator app on 17-May-2022
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_25_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_29_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_32_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_36_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_40_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_45_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_49_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_51_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_55_Pro.jpg',...
    'C:\Users\harma\OneDrive\Documents\Mecha 4\Mech 423\Project\MECH423ProjectChessBoard\Python Code\Calibration_Images\WIN_20220517_20_17_58_Pro.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 44;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
